language: node_js
node_js: '7'

sudo: required
services:
  - docker

env:
  global:
    - secure: 6iuHHcWWbQ0LsAL82j/FaDk0/BEBXITXs5S/9YkteMrX7DhOyps2UAEKDSj0BCETd75NKpXsuOTbhqt2WByZMZFyCoagbMie0ykgXYIjQ3EPO+HrOJOXofnTR94RF6zHBI2NNKVugv+9UJ0DX3h2IlxYW512EmzdhxaWrJCKfBJKl2drtrOLdfaBBw2u5RYb5LLGeNcS2qSMdlNLCQCxV+wrlADXYxaTGsifvADOdc+ZDiLzdDfLMo/ksbwknnizjf2vJ1OTmn4gpAAn01I+eJB1S/d+cBUL1EhgANoE42dXYNh8nXqUuUdh7W1IonOaaL3KKd92tNN0sIqGxFDY0OoxachXx68ex5NBrd8LbQIYmPN64VV2jI4Yb2tMIn245G1vcBwPG04t0dqbGvnxTFyQjjr1smJ35+sH6yTPcSHV3WKwAHqOgSL2gh5yhY5NsUD+mMdeffCXZimRdR5bfTO7SzCRfudLrnIBGm2hbStgZhIExh8LwjZguuTSOmlzVAzr1GLKhRgafGElctLZp/CNEQlq1WBc8H/WMix2W0hv5xNkmfzqfB4S2+EGGlfhyW0y2afsEbyWKeyZPTdhpAc/R/v3gj+qL6QXCQOacWutOolIlQ4MdaqYxw9+9/SXPedZajhDM42NjaF0FTo2EJLsU0BDYbfcdbQM48hMTMc=
    - secure: xhi1K0MrGIdLP1TMB4aK8MX0qMBxVW15XvlJ3a6bvyO3I1A7196diAlVzyu5C+dzVc0fCFHucwhF2THnO1fPp74B9SLymW+F7+rtUT1PKGl45PSF/p83fHrKLu1+1KosbPfFQZmKwHeKtHIGX4ENlshIZnaLL7EeHlqrg6DwURFEY8HH+jhaT/BOkUowTeHd6RYGlNWa7zC26acQ+5bBdaXV3h9QCQpkFnXjBgoe6MjiWEh50Fgrfluv6JpWGi3rhfjViW6ePhL6nX/7MMdXrgQslTmHSzX6XGiUYPeGroIROuBGWwdGL8fWwrZmfLrsW/+KrzF1LeG7ASN6pRw0MU/tBVpNSGR/k9lySZH5jJbgjYUQdH7tQKaQHWISjzf67BA6w4j1WKDrZgCUodTNlHQ7Xv4lVoLFxP2XVq+HvgKtD9piTJkjhzv3tf8SINySaOSOvfaVb/lnELOC7NYGIXkJeuWTyvNxjb4Sb2d2AVlMXWXRxr0mlTVXbysbVe5FxgjzFToLF7HBtbrmjR2NQTVOz7Qp3diNEnuspRTl8FDd4g2bNfUjulPV1Rco1O5QF4J6/1D6wcD38gaO9aK6Z0ivsG9HAQ0JJHMNgdrXTyv0nC823Ilef2Gk1EWGolU3qqMT+DH+yW9kn7SUli4wYFRfEFmoyBNqBQEKP8hWSgo=
    - secure: "lZOqMCJNOxjzuMJzOP5Apiq0hEw9JJDmbBVWjwONQFL3mdZEu1V8pphZvZsf1CtOgrWA4EnO95ervsqCRB/hanKf/hCsPRQDiGqAwyEwn/oOezZpXOO/8xnYi8cMuG3hZthdDoEOb4xyQwe8Gc8dQGkE+nFDq2jObBILFnjhpj5FEbWKqLaVhEbqjbhnE/iOj+7mieYGyhBDFzV3D949sWlSOF5GkA/2BUPrLSVK/nyjxpdq3j6xTDgz0II0LJeEg33piZGe7ME8JZAewVpha835bxRO7d+wIijyPyK/xyAuui5DuwKPmbUkjoWPi0xlTkWgRyPQB3Y6qvSonkCo1laHVCI+bhVbeXriMi76omziNl6L+Xv1r7iHot3Hf7FlyYTrNi8Eg8rxNU7lRrul6osfHy0UM/btzVhvBqGclo1Uf+9uuofRbmIzztNdqwzNC/SLgSETMj912SSML9VbR0N8Q/2TIX7RLbanGo54UFpw5NcIGKfQNMTtprLlafHvpMjc0uzrnV1ZKarknya5jp2ETy+pSrE1O68CfN3PgcCRJCep+VbT1WpVsoG3i3tQjtQMksZmuygT6owKEdIHW8Ca+hbzI3ZHQKnfxdbYq+LS706oOl7PfokIu2Rds+SoHY3C2PdcIPaJZTh0YcNrgBCueO8+6xv9FMjftfhPjVQ="

before_install:
  - openssl aes-256-cbc -K $encrypted_f7b57f904d95_key -iv $encrypted_f7b57f904d95_iv -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - yarn test
  - yarn run build
  - make build
  - make push

# Currently disable this so every commit is pushed to the hub
# deploy:
#   provider: script
#   script: operations/scripts/push.sh

notifications:
  slack:
    secure: QwSscYSX1d60cEGhLN9T6CwN4tds8rFT5tpG6oWxv+OIL62wmk6i7PMtmV86VP1o2hX9VTqFqCfP4FgZEdHZKGLHo5FIhXXdaXqY4vHFQvfIrrbD6FB3b2R7YkNiu+PrQpK6cf4nzvNqXst0yEzGDOghIoIbgc13YL+aYGPSdMF+TkfnfFPD3B+WaMRVqb+G8+6s3bNKni6SP1GDGEIDi1NOFC7dzDzhWmvD1ysKMpPuBZGQ6HTgXXjT1TfLArjyHmsWcbLschRFM5Ies+4Ukw8At/szYdjXD7VWRN9EXKLFmqUnkkTVLN7VZGN+SxNm5iiSMqgx5jxxqpmQLqAxNAxd2pLWGg4urCI6JlHztXDA6rWPJqcbrLRW+K5DUHJUCMV7TxwVgaryVIrnFYRX/WGO4B4KDhk1QcBBjdcgM+YCpvsXaM3j+EdTOSnqTm11BmlOGSYZZk82Cb9TCdhCKC52HxWRBZeG2LJ9VeHCcW2eqeOXoK1pLCz6y52QEzxrgolgcHksl9tlmjhVYH5dGGL99NNcuHLM7b8Ep7h8va3IRIWgbAzYV4IPGpPuhjn63B829piBnn0Ci/OMhyi+bgsZcDUFqeesw5zwqw4hR7FKinsCSWYnlhFy8BVtwvKay6A0LSE76w20J3xqtNh49liNU+4k7/dljTiUojAH1q8=